import { useState, useEffect } from "react";
import { FileDown } from "lucide-react";
import { storage } from "../utils/storage";
import { AnalysisResult } from "../types";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function Reports() {
  const [history, setHistory] = useState<AnalysisResult[]>([]);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = () => {
    setHistory(storage.getAnalysisHistory());
  };

  const handleClearHistory = () => {
    if (confirm("Are you sure you want to clear all analysis history?")) {
      storage.clearHistory();
      loadHistory();
    }
  };

  // ---------------------------------------------------------
  // PDF GENERATION (NO AI DIAGNOSTIC SUMMARY)
  // ---------------------------------------------------------
  const handleDownloadPDF = (analysis: AnalysisResult) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;

    // Title
    doc.setFontSize(20);
    doc.setTextColor(41, 128, 185);
    doc.text("SHAKTI - Component Report", margin, 20);

    // Basic Details
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Component: ${analysis.componentName}`, margin, 40);
    doc.text(
      `Analysis Date: ${new Date(analysis.timestamp).toLocaleString()}`,
      margin,
      50
    );
    doc.text(`Source File: ${analysis.filename}`, margin, 60);

    // Health & RUL Card
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, 70, pageWidth - 40, 30, "F");

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Health Score: ${analysis.health_score.toFixed(1)}%`, margin + 10, 85);
    doc.text(`Estimated RUL: ${analysis.rul_days.toFixed(0)} Days`, margin + 10, 95);

    // Alert Level Color
    if (analysis.alert_level === "OPTIMAL") doc.setTextColor(39, 174, 96);
    else if (analysis.alert_level === "WARNING") doc.setTextColor(243, 156, 18);
    else doc.setTextColor(192, 57, 43);

    doc.text(`Status: ${analysis.alert_level}`, margin + 120, 85);
    doc.setTextColor(0, 0, 0);

    // Table
    doc.text("Critical Risk Factors (Root Cause Analysis):", margin, 120);

    const tableData = analysis.top_factors.map(([factor, impact]) => [
      factor.replace(/_/g, " "),
      `${(impact * 100).toFixed(1)}%`,
    ]);

    autoTable(doc, {
      startY: 125,
      head: [["Factor Name", "Impact Probability"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [41, 128, 185] },
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by AI Predictive Maintenance System", margin, 285);

    // Save PDF
    doc.save(`Report_${analysis.componentName}_${Date.now()}.pdf`);
  };

  const getAlertBadge = (level: string) => {
    const styles = {
      OPTIMAL: "bg-green-100 text-green-700 border-green-200",
      WARNING: "bg-yellow-100 text-yellow-700 border-yellow-200",
      CRITICAL: "bg-red-100 text-red-700 border-red-200",
    };
    return styles[level as keyof typeof styles] || styles.OPTIMAL;
  };

  return (
    <div className="space-y-6 text-slate-900 dark:text-white">
      {history.length > 0 && (
        <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 border-b border-slate-100 dark:border-slate-700">
            <div className="text-sm font-medium">Analysis Reports</div>
            <button
              onClick={handleClearHistory}
              className="px-3 py-1.5 bg-red-50 text-red-600 rounded-md hover:bg-red-100 border dark:bg-slate-700 dark:border-slate-600 dark:text-white"
            >
              Clear History
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-slate-50 dark:bg-slate-700 border-b border-slate-200 dark:border-slate-600">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-semibold">Component</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold">Date</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold">Health</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold">RUL (Days)</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold">Status</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold">Report</th>
                </tr>
              </thead>

              <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                {history.map((analysis) => (
                  <tr key={analysis.id} className="hover:bg-slate-50 dark:hover:bg-slate-700">
                    <td className="px-6 py-4">
                      <div className="font-medium">{analysis.componentName}</div>
                      <div className="text-sm opacity-70">{analysis.filename}</div>
                    </td>

                    <td className="px-6 py-4">
                      {new Date(analysis.timestamp).toLocaleDateString()}
                    </td>

                    <td className="px-6 py-4 font-semibold">
                      {analysis.health_score.toFixed(1)}%
                    </td>

                    <td className="px-6 py-4 font-medium">
                      {analysis.rul_days.toFixed(0)}
                    </td>

                    <td className="px-6 py-4">
                      <span
                        className={`px-3 py-1 rounded-md text-xs font-semibold border ${getAlertBadge(
                          analysis.alert_level
                        )}`}
                      >
                        {analysis.alert_level}
                      </span>
                    </td>

                    <td className="px-6 py-4">
                      <button
                        onClick={() => handleDownloadPDF(analysis)}
                        className="flex items-center space-x-2 px-3 py-1.5 bg-blue-50 text-blue-600 rounded-md hover:bg-blue-100 border dark:bg-slate-700 dark:border-slate-600 dark:text-white"
                      >
                        <FileDown className="w-4 h-4" />
                        <span>PDF</span>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {history.length === 0 && (
        <div className="text-center py-20 opacity-70">No reports available.</div>
      )}
    </div>
  );
}
